<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Prawin-Pc" failures="6" tests="16" name="Default test" time="80.242" errors="0" timestamp="20 Mar 2025 02:25:56 GMT">
  <testcase classname="runner.TestRunner" name="runScenario" time="3.782"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.338"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="9.47"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.787"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.29"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="6.393">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected message not displayed! expected [You successfully transferred $500 from Checking to Savings] but found [You successfully submitted your transaction.],
	Account Balance did not Update! expected [$1048] but found [$1548]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Expected message not displayed! expected [You successfully transferred $500 from Checking to Savings] but found [You successfully submitted your transaction.],
	Account Balance did not Update! expected [$1048] but found [$1548]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at stepDefinitions.FundTransferFunctionality.user_should_see_message(FundTransferFunctionality.java:57)
	at ✽.User should see msg as "You successfully transferred $500 from Checking to Savings" and balance must be updated "yes"(file:///C:/Users/kalai/eclipse-workspace/CAPSTONEPROJECT/src/test/resources/features/03_fundtransfer.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="2.838">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected message not displayed! expected [Insufficient funds.] but found [You successfully submitted your transaction.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Expected message not displayed! expected [Insufficient funds.] but found [You successfully submitted your transaction.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at stepDefinitions.FundTransferFunctionality.user_should_see_message(FundTransferFunctionality.java:57)
	at ✽.User should see msg as "Insufficient funds." and balance must be updated "no"(file:///C:/Users/kalai/eclipse-workspace/CAPSTONEPROJECT/src/test/resources/features/03_fundtransfer.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="2.524">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected message not displayed! expected [Invalid amount entered.] but found [You successfully submitted your transaction.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Expected message not displayed! expected [Invalid amount entered.] but found [You successfully submitted your transaction.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at stepDefinitions.FundTransferFunctionality.user_should_see_message(FundTransferFunctionality.java:57)
	at ✽.User should see msg as "Invalid amount entered." and balance must be updated "no"(file:///C:/Users/kalai/eclipse-workspace/CAPSTONEPROJECT/src/test/resources/features/03_fundtransfer.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="6.564"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.463"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.563">
    <failure type="java.lang.AssertionError" message="Expected message not displayed! expected [Amount field cannot be empty.] but found [Please fill out this field.]">
      <![CDATA[java.lang.AssertionError: Expected message not displayed! expected [Amount field cannot be empty.] but found [Please fill out this field.]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at stepDefinitions.PayBillsFunctionality.user_should_see_the_message(PayBillsFunctionality.java:55)
	at ✽.User should see the "Amount field cannot be empty."(file:///C:/Users/kalai/eclipse-workspace/CAPSTONEPROJECT/src/test/resources/features/04_paybills.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="3.339"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.021">
    <failure type="java.lang.AssertionError" message="Message mismatch! expected [All fields are required.] but found [Please fill out this field.]">
      <![CDATA[java.lang.AssertionError: Message mismatch! expected [All fields are required.] but found [Please fill out this field.]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at stepDefinitions.NewPayeeFunctionality.user_should_see_payee_added_message(NewPayeeFunctionality.java:52)
	at ✽.User should see Payee Added "All fields are required."(file:///C:/Users/kalai/eclipse-workspace/CAPSTONEPROJECT/src/test/resources/features/05_addnewpayee.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="7.022"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.197">
    <failure type="java.lang.AssertionError" message="Logout Successful, But user not directed to login page ! expected [http://zero.webappsecurity.com/login.html] but found [http://zero.webappsecurity.com/index.html]">
      <![CDATA[java.lang.AssertionError: Logout Successful, But user not directed to login page ! expected [http://zero.webappsecurity.com/login.html] but found [http://zero.webappsecurity.com/index.html]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at stepDefinitions.LogoutFunctionality.user_should_be_redirected_to_login_page(LogoutFunctionality.java:32)
	at ✽.User should be redirected to the login page(file:///C:/Users/kalai/eclipse-workspace/CAPSTONEPROJECT/src/test/resources/features/07_logout.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="0.592"/>
</testsuite> <!-- Default test -->
